@startuml
@startmindmap
caption GITOPS
title GITOPS IMPLEMENTATION WITH GCP

<style>
mindmapDiagram {
  node {
    BackgroundColor lightGreen
  }
 :depth(1) {
      BackGroundColor Orange
    }
  :depth(2) {
      BackGroundColor LightGoldenRodYellow
    }
  :depth(3) {
      BackGroundColor LightCoral
    }      
}
</style>
* GITOPS
** Source Repo => Github
** IaC => Terraform
*** InfraState => GCS
**** DB => AlloyDB
**** NETWORK => VPC
**** APP-TIER => GKE
**** WEB-TIER => GCP LoadBalancer
** CI => Cloud Build
*** RepoIntegration => Github
*** Setup Build Trigger
** CD => Cloud Deploy
*** Setup => Delivery Pipeline
*** Setup => Target
*** Setup => Skaffold
** App Deployment => GKE
*** Deployment
*** Services
*** HPA
@endmindmap
@enduml