apiVersion: v1

kind: Service

metadata:
  name: nginx-service
  namespace: stage
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "stage-nginx-service-80-neg"}}}'
  labels:
    app: nginx-service
  
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-pod
status:
  loadBalancer: {}
